CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255) NOT NULL,
  password CHAR(128) NOT NULL,
  socket_id CHAR(20) UNIQUE
);

CREATE TABLE messages (
  id CHAR(36) PRIMARY KEY,
  sender_id CHAR(36) REFERENCES users(id) ON DELETE CASCADE,
  receiver_id CHAR(36) REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);